name: RoleSync
version: 2.0
api-version: 1.16
author: dode5656
main: io.github.dode5656.rolesync.RoleSync
description: Plugin that links discord and minecraft and gives roles to the user in the server's discord.
softdepend:
  - LuckPerms
commands:
  sync:
    usage: /<command> [name]
    aliases: []
  syncreload:
    permission: rolesync.reload
    usage: /<command> [name]
    aliases: []
  unsync:
    usage: /<command> [name]
    aliases: []
